version: '3.8'

services:
  # Redis for Sessions
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Main Application Server
  main_server:
    build: .
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - redis
    deploy:
      replicas: 2 # Scale 2 replicas if needed
    environment:
      - ENV=production

  # Nginx for Load Balancing
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - main_server

volumes:
  static_volume:
  media_volume:
